import "./globals.css";
import { Poppins } from "next/font/google";

export const metadata = {
  title: "Prueba Tecnica",
  description: "Generated by Next.js",
};

const poppins = Poppins({
  weight: ["100","200","300","400","500","600","700","800"],
  subsets: ['latin'], 
})

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={poppins.className}>{children}</body>
    </html>
  );
}
