import "./globals.css";
import ClientHelper from "@/components/clientComponent";
export const metadata= {
  title: "Prueba Tecnica",
  description: "Generated by Next.js",
};

function RootLayout({ children }) {
  return (
      <ClientHelper>
        {children}
      </ClientHelper>
    
  );
}

export default RootLayout;
